# Generated by Django 4.0.3 on 2022-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('parkId', models.IntegerField(primary_key=True, serialize=False)),
                ('MondaytoFriday', models.CharField(max_length=70)),
                ('WeekendHolidays', models.CharField(max_length=70)),
            ],
        ),
    ]
