# Generated by Django 4.0.3 on 2022-05-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timings',
            old_name='MondaytoFriday',
            new_name='monday_to_friday',
        ),
        migrations.RenameField(
            model_name='timings',
            old_name='parkId',
            new_name='park_Id',
        ),
        migrations.RenameField(
            model_name='timings',
            old_name='WeekendHolidays',
            new_name='weekend_and_holidays',
        ),
    ]
