# Generated by Django 4.0.3 on 2022-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnfoodapp', '0002_rename_mondaytofriday_timings_monday_to_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('park_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('child_under_33i', models.CharField(max_length=70)),
                ('child_between_33i_to_4f_6i', models.CharField(max_length=70)),
                ('child_above_4f_6i', models.CharField(max_length=70)),
                ('stag', models.CharField(max_length=70)),
            ],
        ),
    ]
