# Generated by Django 4.0.3 on 2022-05-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnfoodapp', '0004_funnfood_delete_tickets_delete_timings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunnFood',
            new_name='Fun_N_Food',
        ),
    ]
