# Generated by Django 4.0.3 on 2022-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnfoodapp', '0005_rename_funnfood_fun_n_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('park_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('child_under_33i', models.CharField(max_length=70)),
                ('child_between_33i_to_4f_6i', models.CharField(max_length=70)),
                ('child_above_4f_6i', models.CharField(max_length=70)),
                ('stag', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('park_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('monday_to_friday', models.CharField(max_length=70)),
                ('weekend_and_holidays', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Fun_N_Food',
        ),
    ]
