# Generated by Django 4.0.3 on 2022-05-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnfoodapp', '0006_tickets_timings_delete_fun_n_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='Timings',
            new_name='Timing',
        ),
    ]
